//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public Choice()
        {
            this.StudentQuestionChoices = new HashSet<StudentQuestionChoice>();
        }
    
        public decimal ChoiceID { get; set; }
        public Nullable<int> AnswerNo { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> iscorrect { get; set; }
        public Nullable<decimal> QuestionID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual ICollection<StudentQuestionChoice> StudentQuestionChoices { get; set; }
    }
}
