//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        public Examination()
        {
            this.Questions = new HashSet<Question>();
            this.StudentExams = new HashSet<StudentExam>();
        }
    
        public decimal ExamID { get; set; }
        public string ExamName { get; set; }
        public string ExamNote { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<bool> HasCommonEnroll { get; set; }
        public string EnrollKey { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<decimal> TutorID { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Tutor Tutor { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<StudentExam> StudentExams { get; set; }
    }
}
