//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionStatu
    {
        public QuestionStatu()
        {
            this.StudentQuestions = new HashSet<StudentQuestion>();
        }
    
        public int QuestionStatusID { get; set; }
        public string QuestionStatus { get; set; }
    
        public virtual ICollection<StudentQuestion> StudentQuestions { get; set; }
    }
}
