//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentQuestion
    {
        public StudentQuestion()
        {
            this.StudentQuestionChoices = new HashSet<StudentQuestionChoice>();
        }
    
        public decimal StuQuesID { get; set; }
        public Nullable<decimal> QuestionID { get; set; }
        public Nullable<decimal> StudentID { get; set; }
        public Nullable<int> QuestionStatusID { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Question Question { get; set; }
        public virtual QuestionStatu QuestionStatu { get; set; }
        public virtual ICollection<StudentQuestionChoice> StudentQuestionChoices { get; set; }
    }
}
