//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExam
    {
        public decimal STEXID { get; set; }
        public Nullable<decimal> ExamID { get; set; }
        public Nullable<decimal> StudentID { get; set; }
        public string EnrollKey { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Examination Examination { get; set; }
    }
}
