//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Examinations = new HashSet<Examination>();
        }
    
        public int SubjectID { get; set; }
        public Nullable<int> SubjectCategoryID { get; set; }
        public string SubjectName_en { get; set; }
        public string SubjectName_si { get; set; }
    
        public virtual ICollection<Examination> Examinations { get; set; }
        public virtual SubjectCategory SubjectCategory { get; set; }
    }
}
