//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectCategory
    {
        public SubjectCategory()
        {
            this.Subjects = new HashSet<Subject>();
        }
    
        public int SubjectCategoryID { get; set; }
        public string SubjectCategoryName_en { get; set; }
        public string SubjectCategoryName_si { get; set; }
    
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}
